In [66]:
import tensorflow as tf
import numpy as np

X = tf.placeholder("float", [None,2]) 
Y = tf.placeholder("float",[None,1])

def init_weights(shape):
    return tf.Variable(tf.random_normal(shape, stddev=0.01))

def model(X, W, b):
    return tf.add(tf.matmul(X, W), b) 

W = init_weights([2,1])
b = init_weights([1])

y_model = model(X, W, b)

cost = tf.square(Y - y_model) 
pred = tf.add(tf.matmul(X, W), b) 

train_op = tf.train.GradientDescentOptimizer(0.01).minimize(cost) 


In [67]:
trX = np.array([[0,0],[0,1],[1,0],[1,1]])
trY_OR = np.array([[0],[1],[1],[1]])
trY_AND = np.array([[0],[0],[0],[1]])
trY_XNOR = np.array([[1],[0],[0],[1]])
trY_NOR = np.array([[1],[0],[0],[0]])
trY_NAND = np.array([[1],[1],[1],[0]])
trY_XOR = np.array([[0],[1],[1],[0]])



In [68]:
# [0 1 1 1] 
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_OR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[ 0.49999899],
       [ 0.49999899]], dtype=float32), array([ 0.25000119], dtype=float32)]
[[ 0.25000119]
 [ 0.75000018]
 [ 0.75000018]
 [ 1.24999917]]


In [69]:
# [0 0 0 1]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_AND})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[ 0.49999872],
       [ 0.49999872]], dtype=float32), array([-0.24999844], dtype=float32)]
[[-0.24999844]
 [ 0.2500003 ]
 [ 0.2500003 ]
 [ 0.74999899]]


In [70]:
# [0 1 1 0]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_XOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[  6.45183263e-07],
       [  6.45090495e-07]], dtype=float32), array([ 0.49999917], dtype=float32)]
[[ 0.49999917]
 [ 0.49999982]
 [ 0.49999982]
 [ 0.50000048]]


In [71]:
# [1 0 0 1]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_XNOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[  6.34816161e-07],
       [  6.35073548e-07]], dtype=float32), array([ 0.4999992], dtype=float32)]
[[ 0.4999992 ]
 [ 0.49999982]
 [ 0.49999982]
 [ 0.50000048]]


In [72]:
#[1 0 0 0]
with tf.Session() as sess:
    # you need to initialize variables (in this case just variable W)
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_NAND})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[-0.49999732],
       [-0.49999732]], dtype=float32), array([ 1.24999654], dtype=float32)]
[[ 1.24999654]
 [ 0.74999923]
 [ 0.74999923]
 [ 0.25000191]]


In [73]:
#[1 1 1 0 ]
with tf.Session() as sess:
    # you need to initialize variables (in this case just variable W)
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_NOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[-0.49999791],
       [-0.49999791]], dtype=float32), array([ 0.74999756], dtype=float32)]
[[ 0.74999756]
 [ 0.24999964]
 [ 0.24999964]
 [-0.24999827]]
