In [2]:
import tensorflow as tf
import numpy as np

X = tf.placeholder("float", [None,2]) 
Y = tf.placeholder("float",[None,1])

def init_weights(shape):
    return tf.Variable(tf.random_normal(shape, stddev=0.01))

def model(X, W, b):
    return tf.sigmoid(tf.add(tf.matmul(X, W), b)) 

# Set model weights
W = init_weights([2,1])
b = init_weights([1])

y_model = model(X, W, b)

cost = tf.square(Y*tf.log(y_model)+ (1-Y)*tf.log(1-y_model)) 

pred = tf.add(tf.matmul(X, W), b) 

train_op = tf.train.GradientDescentOptimizer(0.01).minimize(cost) 


In [3]:
trX = np.array([[0,0],[0,1],[1,0],[1,1]])
trY_OR = np.array([[0],[1],[1],[1]])
trY_AND = np.array([[0],[0],[0],[1]])
trY_XNOR = np.array([[1],[0],[0],[1]])
trY_NOR = np.array([[1],[0],[0],[0]])
trY_NAND = np.array([[1],[1],[1],[0]])
trY_XOR = np.array([[0],[1],[1],[0]])




In [4]:
# [0 1 1 1] 
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_OR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[ 2.11612463],
       [ 2.11422372]], dtype=float32), array([-0.763524], dtype=float32)]
[[-0.763524  ]
 [ 1.35069966]
 [ 1.35260057]
 [ 3.46682453]]


In [7]:
# [0 0 0 1]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_AND})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[ 1.59153688],
       [ 1.5917623 ]], dtype=float32), array([-2.50461578], dtype=float32)]
[[-2.50461578]
 [-0.91285348]
 [-0.9130789 ]
 [ 0.67868328]]


In [14]:
# [0 1 1 0]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_XOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[  1.61750340e-05],
       [  8.43698399e-06]], dtype=float32), array([ -1.46142602e-05], dtype=float32)]
[[ -1.46142602e-05]
 [ -6.17727619e-06]
 [  1.56077385e-06]
 [  9.99775784e-06]]


In [18]:
# [1 0 0 1]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_XNOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[  9.41407325e-06],
       [  7.02774287e-06]], dtype=float32), array([ -9.72456382e-06], dtype=float32)]
[[ -9.72456382e-06]
 [ -2.69682096e-06]
 [ -3.10490577e-07]
 [  6.71725229e-06]]


In [19]:
# [1 0 0 0]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_NAND})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[-1.59169388],
       [-1.59154916]], dtype=float32), array([ 2.5045743], dtype=float32)]
[[ 2.5045743 ]
 [ 0.91302514]
 [ 0.91288042]
 [-0.67866874]]


In [24]:
# [1 1 1 0]
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(trX.shape)
    for i in range(1000):
        _,c = sess.run([train_op, cost], feed_dict={X: trX, Y: trY_NOR})
        ans = sess.run(pred, feed_dict={X:trX})
    print(sess.run([W,b]))
    print(ans)

(4, 2)
[array([[-2.11868954],
       [-2.11856294]], dtype=float32), array([ 0.76538628], dtype=float32)]
[[ 0.76538628]
 [-1.35317659]
 [-1.35330319]
 [-3.47186589]]
